export LC_ALL=zh_CN.UTF-8

export PATH=$PATH:$HOME/bin
export PATH=$PATH:/Users/chuqq/go/bin
export HOMEBREW_BOTTLE_DOMAIN=https://mirrors.ustc.edu.cn/homebrew-bottles
export GOPATH=/Volumes/work/go

export PATH="/usr/local/sbin:$PATH"
export PATH=$PATH:/usr/local/opt/go/libexec/bin

